### ISSUE TITLE
java/simple-cli fails on Java 8

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-examples#100]
When I try to run `java/simple-cli` on Java 1.8.0_60, I get the following exception:

```
2015-09-29 15:29:36,938 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-09-29 15:29:37,147 INFO  [main] grpc.BigtableSession: Opening connection for projectId jefesaurus-bigtable, zoneId us-central1-b, clusterId test-cluster, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:90)
	at com.example.bigtable.simplecli.HBaseCLI.main(HBaseCLI.java:129)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
	... 3 more
Caused by: java.io.IOException: Could not initialize credentials
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:343)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:283)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:232)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:133)
	at com.google.cloud.bigtable.hbase1_1.BigtableConnection.<init>(BigtableConnection.java:42)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: sun.security.ssl.ClientHandshaker.getRawHostnameSE()Ljava/lang/String;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:336)
	... 12 more
Caused by: java.lang.NoSuchMethodError: sun.security.ssl.ClientHandshaker.getRawHostnameSE()Ljava/lang/String;
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1397)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1487)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.bigtable.repackaged.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:222)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:232)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.syncRefresh(RefreshingOAuth2CredentialsInterceptor.java:166)
	at com.google.cloud.bigtable.grpc.BigtableSession$7.call(BigtableSession.java:302)
	at com.google.cloud.bigtable.grpc.BigtableSession$7.call(BigtableSession.java:299)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

When I update `alpn.version` to `8.1.5.v20150921` in the `pom.xml` file, the error goes away.

**Comment by sduskis** [comment]
You can't just switch the jar, because then JDK 1.7 won't work.  We need to solve this via documentation about ALPN usage with CBT rather than a pom.xml change.

**Comment by hegemonic** [comment]
Right, I didn't mean to suggest that I'd found the definitive solution to this issue.

I guess I was hoping that we could use one version of the ALPN JAR on Java 7 and another version on Java 8. Is it possible to set up the `pom.xml` file that way?

**Comment by sduskis** [comment]
I'm working on a pom.xml solution for alpn now in cloud-bigtable-client.

**Comment by lesv** [comment]
This was fixed in my last PR.
