### ISSUE TITLE
ScanRetriesExhaustedException when reading from bigtable in a managed VM setup

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-examples#145]
I am not able to do any bigtable operations from the managed VM setup. The bigtable operations are working fine from my local machine, but timeout on the cloud(Managed VM). The setup was working fine on managed VM as well till yesterday.

I followed the steps as given here, and the setup was working fine for a couple of months (till yesterday, when I started getting timeouts consistently).

I am using version 0.2.2 of cloud-bigtable-client with hbase1.1 (also version 0.2.2).

The error I get in the log is:
Caused by: com.google.cloud.bigtable.grpc.scanner.ScanRetriesExhaustedException: Exhausted streaming retries.
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.backOffAndRetry(ResumingStreamingResultScanner.java:142)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:112)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:42)
at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
... 11 more
Caused by: com.google.cloud.bigtable.grpc.scanner.ScanTimeoutException: Timeout while merging responses.
at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNext(ResponseQueueReader.java:113)
at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:64)
at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:64)
at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:28)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:101)
... 14 more

**Comment by vc13819** [comment]
Exception in thread "pool-2-thread-2" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshak
er.localSupportedSignAlgs from class sun.security.ssl.ClientHandshaker
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection
.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1093)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at com.google.bigtable.repackaged.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.
java:77)
        at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
        at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:222)
        at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(Ref
reshingOAuth2CredentialsInterceptor.java:268)
        at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2Crede
ntialsInterceptor.java:238)
        at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$1.run(RefreshingOAuth2Credentia
lsInterceptor.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vc13819** [comment]
Tried upgrading to bigtable client 0.2.3. This is the error I am getting now. (I have 'com.google.auth:google-auth-library-appengine:0.3.1' in the classpath)

Caused by: java.io.IOException: Application Default Credentials failed to create the Google App Engine service account credentials class com.google.bigtable.repackaged.com.google.auth.appengine.AppEngineCredentials. Check that the component 'google-auth-library-appengine' is deployed.
	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.tryGetAppEngineCredential(DefaultCredentialsProvider.java:241)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:138)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:67)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:54)
	at com.google.cloud.bigtable.config.CredentialFactory.getApplicationDefaultCredential(CredentialFactory.java:181)
	at com.google.cloud.bigtable.config.CredentialFactory.getCredentials(CredentialFactory.java:100)
	at com.google.cloud.bigtable.grpc.io.CredentialInterceptorCache.getCredentialsInterceptor(CredentialInterceptorCache.java:85)
	at com.google.cloud.bigtable.grpc.BigtableSession$6.call(BigtableSession.java:317)
	at com.google.cloud.bigtable.grpc.BigtableSession$6.call(BigtableSession.java:309)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.google.bigtable.repackaged.com.google.auth.appengine.AppEngineCredentials
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.forName(DefaultCredentialsProvider.java:266)
	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.tryGetAppEngineCredential(DefaultCredentialsProvider.java:225)
	... 12 more

**Comment by lesv** [comment]
The latest version of managed-vm-gae example uses 0.2.3 w/ netty boring SSL static.

**Comment by vc13819** [comment]
I do have netty boring SSL in the classpath.  I was able to get the setup to work, however yesterday the servers again stopped working (Without any update to the servers). This is the gradle file
I am using. (I was using version 0.2.3. I have now retried with 0.2.3 and 0.2.4, couldnt get either to work).

  appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.34'
  compile 'com.google.appengine:appengine-endpoints:1.9.34'
  compile 'com.google.appengine:appengine-endpoints-deps:1.9.34'
  compile 'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork13:linux-x86_64'
  compile 'com.google.auth:google-auth-library-appengine:0.3.1'
  compile 'com.google.auth:google-auth-library-credentials:0.3.1'
  compile 'com.google.auth:google-auth-library-oauth2-http:0.3.1'
  compile 'com.google.cloud.bigtable:bigtable-client:0.2.4'
  compile 'com.google.cloud.bigtable:bigtable-hbase-1.1:0.2.4'

**Comment by vc13819** [comment]
Finally got it to work. Had to put in GOOGLE_APPLICATION_CREDENTIALS in the appengine-web.xml.

**Comment by lesv** [comment]
Glad it worked for you, but that shouldn't be necessary.  Is your Cloud Bigtable Cluster in a different project?  If so, you can add your project as an editor of that and get access.

**Comment by vc13819** [comment]
Our cloud bigtable cluster is in the same project. The setup is rather
vanilla, very similar (AFAICT to the one in managed-vm-gae example. I have
tried to mimic that in our setup. I can get the example to work, but not
our setup w/o having to specify the GOOGLE_APPLICATION_CREDENTIALS var,
which does look like a hack).

The classnotfoundexception is telling though, because the package name has
bigtable.repackaged, it appears that there are some classes that should be
shaded and part of the cloud-bigtable-jars that have gotten missed.

Thanks for your responses
Vinay

**Comment by lesv** [comment]
@sduskis Can you suggest anything?

Do you have all the Bigtable API's enabled?  Are you using IAM?

**Comment by sduskis** [comment]
I'll google-auth-library-appengine to our pom.xml as a shaded and included jar.  That may help.

**Comment by sduskis** [comment]
I deployed a new version of cloud-bigtable 0.2.5-SNAPSHOT that has the google-auth-library-appengine dependency.

**Comment by vc13819** [comment]
@sduskis Many thanks. This fixes the issue. I was able to get our setup working w/o the need for GOOGLE_APPLICATION_CREDENTIALS.

**Comment by vc13819** [comment]
Spoke too soon...approximately 10% of the queries are giving this error
java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.yawasa.server.storage.TopicTable.freeFutures(TopicTable.java:109)
	at com.yawasa.server.storage.TopicTable.get(TopicTable.java:96)
	at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:299)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:97)
	at com.yawasa.server.storage.TopicPopulator.get(TopicPopulator.java:50)
	at com.yawasa.server.storage.TopicTable.get(TopicTable.java:118)
	at com.yawasa.server.storage.TopicTable.access$000(TopicTable.java:41)
	at com.yawasa.server.storage.TopicTable$1.call(TopicTable.java:88)
	at com.yawasa.server.storage.TopicTable$1.call(TopicTable.java:85)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	... 1 more
Caused by: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:66)
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:69)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:42)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:27)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:158)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:44)
	at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
	... 11 more
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials.
	at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:431)
	at com.google.cloud.bigtable.grpc.scanner.ReadRowsResponseListener.onClose(ReadRowsResponseListener.java:72)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
	at com.google.bigtable.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at com.google.bigtable.repackaged.io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)

**Comment by vc13819** [comment]
FWIW your managed-vm-gae example requires a google sign in...a test case which does not require a user sign in..and just rely of service account would nail the problem....
I tried it with a test case..and had production reports about failures an hour after...:(

**Comment by lesv** [comment]
@sduskis - I suspect it's unrelated, but we just ran across [this](https://github.com/GoogleCloudPlatform/gcloud-java/issues/827).

**Comment by sduskis** [comment]
@lesv: Is there anything I need to do for this bug?  I'm not sure about how managed vms work.

**Comment by lesv** [comment]
No - this sounds like it's something for me - at least initially - not sure what I was thinking when I asked you to look at it.

@vc13819 - you encountered issues after an hour - was it a single long running session (ie. no chance for an explicit credential refresh)?  Or were you doing multiple connections.

**Comment by vc13819** [comment]
On Wed, Apr 6, 2016 at 12:36 AM, Les Vogel <notifications@github.com> wrote:

> No - this sounds like it's something for me - at least initially - not
> sure what I was thinking when I asked you to look at it.
>
> @vc13819 <https://github.com/vc13819> - you encountered issues after an
> hour - was it a single long running session (ie. no chance for an explicit
> credential refresh)? Or were you doing multiple connections.
>
It was a single session. We are running 2 instances of the server, and they
both started failing after about an hour.
We did not do any explicit credentials refresh.
With the GOOGLE_APPLICATION_CREDENTIALS things have continued to work
without hiccups (touchwood!!)

**Comment by sduskis** [comment]
There's a bug in the AppEngineCredentials handling of expiration.  There's a default expiration of about 1 hour.  That expiration information is not being passed around correctly.  I submitted a fix for that problem, so that the refreshing logic can kick in and fix the problem.

**Comment by lesv** [comment]
This requires the updated client to be fixed it should be in 0.2.5-SNAPSHOT now if you wish to try it.

**Comment by lesv** [comment]
Fixed
