### ISSUE TITLE
When using the hbase cli quickstart, 'getting' a nonexistent key yields an NPE

### ISSUE THREAD

**Issue by ianlewis** [GoogleCloudPlatform/cloud-bigtable-examples#150]
$  ./hbasecli.sh get pi 3141592653
...
Exception in thread "main" java.lang.NullPointerException
    at com.example.bigtable.simplecli.HBaseCLI$GetCommand.run(HBaseCLI.java:386)
    at com.example.bigtable.simplecli.HBaseCLI.main(HBaseCLI.java:138)

**Comment by lesv** [comment]
Do you want to fix this?

**Comment by meredithslota** [comment]
Deprioritized, closing. If anyone feels strongly about this, please reply/reopen! :)
