### ISSUE TITLE
Could not create table

### ISSUE THREAD

**Issue by yaraju** [GoogleCloudPlatform/cloud-bigtable-examples#210]
**I tried following the instructions to submit a job.**
 gcloud dataproc jobs submit hadoop     --cluster hadoop1     --jar target/wordcount-mapreduce-0-SNAPSHOT-jar-with-dependencies.jar     wordcount-hbase     /input     blah

**I got the following error:**

16/12/08 19:24:19 ERROR sample.CreateTable: Could not figure out if table blah exists.
java.io.IOException: Failed to listTables
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.requestTableList(AbstractBigtableAdmin.java:258)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:245)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:206)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:198)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.tableExists(AbstractBigtableAdmin.java:140)
    at com.example.bigtable.sample.CreateTable.tableExists(CreateTable.java:89)
    at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:64)
    at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
    at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
    at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
    at com.example.bigtable.sample.WordCountDriver.main(WordCountDriver.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
    at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: (475580530846,hadoop1)
    at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:503)
    at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:207)
    at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
    at com.google.bigtable.admin.v2.BigtableTableAdminGrpc$BigtableTableAdminBlockingStub.listTables(BigtableTableAdminGrpc.java:425)
    at com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.listTables(BigtableTableAdminGrpcClient.java:52)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.requestTableList(AbstractBigtableAdmin.java:256)
    ... 22 more
16/12/08 19:24:20 ERROR sample.CreateTable: Could not create table blah
java.io.IOException: Failed to create table 'blah'
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:365)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:322)
    at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:73)
    at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
    at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
    at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
    at com.example.bigtable.sample.WordCountDriver.main(WordCountDriver.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
    at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: (475580530846,hadoop1)
    at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:503)
    at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:207)
    at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
    at com.google.bigtable.admin.v2.BigtableTableAdminGrpc$BigtableTableAdminBlockingStub.createTable(BigtableTableAdminGrpc.java:419)
    at com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.createTable(BigtableTableAdminGrpcClient.java:64)
    at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:358)
    ... 18 more

**More detailed log available here:**
http://pastebin.com/tT4hnf79

**Comment by sduskis** [comment]
Here's the crux of the problem:

NOT_FOUND: Failed to read: (475580530846, hadoop1)


I'm guessing that you didn't create a Bigtable cluster.  475580530846 is
your Google Cloud project id, and hadoop1 is the name you configured as the
name of your Cloud Bigtable instance.  I'm guessing that you named your
Dataproc cluster hadoop1.  Dataproc is a separate environment from Cloud
Bigtable.  Follow this guide
<https://cloud.google.com/bigtable/docs/quickstart-cbt> to create a Cloud
Bigtable cluster, and confirm that you can run operations against the
cluster.  After that, you can run reconfigure your wordcount example to use
the new Cloud Bigtable cluster.

**Comment by yaraju** [comment]
Thanks for the reply!

I've been trying the instructions from:
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/dataproc-wordcount

The documentation needs some update that bigtable cluster needs to be created separately before running it.

**Comment by sduskis** [comment]
We do have the following text on the page:

   - Create a Cloud Bigtable Cluster

I guess it's not prominent enough. Sorry about the confusion.

**Comment by yaraju** [comment]
I noticed it on a closer look, and was able to run the code successfully. Thank you so much for your prompt replies! :+1:
