### ISSUE TITLE
error in using hbasecli.sh list, got a class not found exception

### ISSUE THREAD

**Issue by zhihuawensc** [GoogleCloudPlatform/cloud-bigtable-examples#250]
I followed the instructions at https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/simple-cli

But got the following exceptions while trying to run "./hbasecli.sh list" on a mac laptop, is this expected?

:~/cloud-bigtable-examples/java/simple-cli$ ./hbasecli.sh list
2017-09-20 13:37:56,714 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.io.IOException: java.lang.ClassNotFoundException: com.google.cloud.bigtable.hbase1_2.BigtableConnection
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:230)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:90)
        at com.example.bigtable.simplecli.HBaseCLI.main(HBaseCLI.java:129)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.bigtable.hbase1_2.BigtableConnection
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:228)
        ... 3 more

**Comment by meredithslota** [comment]
Closing this as https://github.com/googleapis/java-bigtable-hbase exists now and any issues re: using Bigtable and HBase should be filed there.
