### ISSUE TITLE
dataproc-wordcount 

### ISSUE THREAD

**Issue by msaadsadiq** [GoogleCloudPlatform/cloud-bigtable-examples#251]
Following the guide successfully at every step. I am able to connect to HBase and modify tables in BigTable. 
https://cloud.google.com/bigtable/docs/creating-hadoop-cluster

But when I submit the Hadoop job on my DataProc cluster, its not able to create new table in BigTable. 

Please Help

git clone https://github.com/GoogleCloudPlatform/cloud-bigtable-examples.git
cd cloud-bigtable-examples/java/dataproc-wordcount
mvn clean package -Dbigtable.projectID=`redacted` -Dbigtable.instanceID=`redacted`
./cluster.sh start trialcluster

Job [300d35c9-024a-4d72-8ac1-e9d188da1231] submitted.
Waiting for job output...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/300d35c9-024a-4d72-8ac1-e9d188da1231/wordcount-mapreduce-0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/10/02 23:12:23 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.1-hadoop2
17/10/02 23:12:23 INFO sample.CreateTable: Creating Table WordCount-1506985932
17/10/02 23:12:23 ERROR sample.WordCountHBase: Could not create the table.
java.io.IOException: java.lang.ClassNotFoundException: com.google.cloud.bigtable.hbase1_2.BigtableConnection
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:230)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:60)
        at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
        at com.example.bigtable.sample.WordCountDriver.main(WordCountDriver.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
        at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.bigtable.hbase1_2.BigtableConnection
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:228)

**Comment by sduskis** [comment]
I apologize.  That was my fault.  I'll take care of the problem tomorrow in github itself.  For now, I suggest changing your local [./src/main/resources/hbase-site.xml](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/dataproc-wordcount/src/main/resources/hbase-site.xml#L28) file.  This line:

`<value>com.google.cloud.bigtable.hbase1_2.BigtableConnection</value>`

should be changed to

`<value>com.google.cloud.bigtable.hbase1_x.BigtableConnection</value>`
