### ISSUE TITLE
Cannot connect to Bigtable API with service account -SSLHandshakeException

### ISSUE THREAD

**Issue by alinaradu** [GoogleCloudPlatform/cloud-bigtable-examples#256]
I am trying to run the **java/hello-world** sample as a standalone application into a local environement.
I created a Service Account, saved the key file and passed it as an GOOGLE_APPLICATION_CREDENTIALS environment variable, as described here: [https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application](url).

However, my SSL handshake fails and the sample cannot connect to the Bigtable instance in my project.
The stacktrace bellow.
I am  stuck. The sample works well when deployed in the Google node itself.
Thank you!

oct. 12, 2017 4:33:03 PM com.google.api.client.http.HttpRequest execute
AVERTISSEMENT: exception thrown while executing request
javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:365)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentials(RefreshingOAuth2CredentialsInterceptor.java:379)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.access$100(RefreshingOAuth2CredentialsInterceptor.java:60)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$2.call(RefreshingOAuth2CredentialsInterceptor.java:328)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$2.call(RefreshingOAuth2CredentialsInterceptor.java:325)

**Comment by alinaradu** [comment]
This was a proxy/firewall problem.
If behind a proxy/firewall, try to go through another network to test the functioning.
