### ISSUE TITLE
UNAUTHENTICATED trying to autoscale bigtable nodes with app engine cron job

### ISSUE THREAD

**Issue by stiancognite** [GoogleCloudPlatform/cloud-bigtable-examples#258]
I'm using [this metric-scaler example](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/metric-scaler). When I get to [the line that says `response = metricServiceClient.listTimeSeries(projectName, filter, interval, TimeSeriesView.FULL);`](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/metric-scaler/src/main/java/com/example/bigtable/scaler/MetricScaler.java#L153) I get an unauth error and this stack trace:
```
com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: UNAUTHENTICATED
	at com.google.api.gax.grpc.ExceptionTransformingCallable$ExceptionTransformingFuture.onFailure(ExceptionTransformingCallable.java:108)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:52)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:451)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:427)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:419)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:60)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:493)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:422)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:525)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 15 more
Caused by: java.io.IOException: Could not get the access token.
	at com.google.auth.oauth2.AppEngineCredentials.refreshAccessToken(AppEngineCredentials.java:136)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:149)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:135)
	at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.run(GoogleAuthLibraryCallCredentials.java:95)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.auth.oauth2.AppEngineCredentials.refreshAccessToken(AppEngineCredentials.java:131)
	... 10 more
Caused by: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call memcache.Get in a thread that is neither the original request thread nor a thread created by ThreadManager
	at com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:844)
	at com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:183)
	at com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:180)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:28)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.get(MemcacheServiceImpl.java:51)
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessToken(AppIdentityServiceImpl.java:300)
	... 15 more
```

Is there something special I have to do because I'm running this in app engine standard?

**Comment by stiancognite** [comment]
Could [google-cloud-java/issues/2504](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2504) be relevant?

**Comment by stiancognite** [comment]
Looks like it! Doing this made it work:
```
    List<String> scopes = Arrays.asList("https://www.googleapis.com/auth/monitoring");
    AppIdentityService appIdentityService = AppIdentityServiceFactory
        .getAppIdentityService();
    // This has to be called:
    String access_token = appIdentityService
        .getAccessToken(scopes)
        .getAccessToken();
    CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(
        GoogleCredentials.getApplicationDefault().createScoped(scopes));
    ChannelProvider channelProvider = MetricServiceSettings
        .defaultChannelProviderBuilder().setCredentialsProvider(credentialsProvider).build();
    MetricServiceSettings metricServiceSettings = MetricServiceSettings
        .defaultBuilder()
        .setChannelProvider(channelProvider)
        .build();
    metricServiceClient = MetricServiceClient
        .create(metricServiceSettings);
```

**Comment by stiancognite** [comment]
Does this code return the very latest cpu load metric, or does it return an average over the last five minutes?
```
  /**
   * Retrieves the latest value for the metric defined by {@link #CPU_METRIC}.
   * @return
   * @throws IOException
   */
  Point getLatestValue() throws IOException {
    // [START get_bigtable_cpu]
    Timestamp now = timeXMinutesAgo(0);
    Timestamp fiveMinutesAgo = timeXMinutesAgo(5);
    TimeInterval interval =
        TimeInterval.newBuilder().setStartTime(fiveMinutesAgo).setEndTime(now).build();
    String filter = "metric.type=\"" + CPU_METRIC + "\"";
    ListTimeSeriesPagedResponse response =
        metricServiceClient.listTimeSeries(projectName, filter, interval, TimeSeriesView.FULL);
    return response.getPage().getValues().iterator().next().getPointsList().get(0);
    // [END get_bigtable_cpu]
  }
```
I see it's doumented as retreiving the latest value. How should I modify this to get an average value?

**Comment by stiancognite** [comment]
The [workaround](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/258#issuecomment-337872123) no longer seems to work as we're seeing unauth-errors again. This should work without doing anything explicit with regards to authentication, right?

**Comment by sduskis** [comment]
UNAUTHENTICATED issues can happen even if everything is set up correctly for long running systems.  I have a couple of suggestions:

- We should recreate the metricServiceClient every invocation.  Hopefully that also gets a new auth token.
- We should probably upgrade the example's version of google-cloud-monitoring, but that's not likely going to help with the UNAUTHENTICATED issue
- A bug should be raised on the [google-cloud-java](https://github.com/GoogleCloudPlatform/google-cloud-java) GitHub project if the problem persists.

**Comment by stiancognite** [comment]
Thank you for taking the time to respond! :) About your first suggestion: Could I verify that that's a problem just by restarting the instance? New app -> new invocation -> new metricServiceClient -> auth should be ok?

What I thought I'd do when I get to work tomorrow is to:
1. Try using the latest versions of all dependencies. Right now I'm using the versions used in the example.
2. Look into using service accounts.

**Comment by sduskis** [comment]
Yup, that's what I meant.  The metricServiceClient should also be closed.  Ideally, creating a new metricServiceClient also means creating a new auth token under the covers.

Service accounts may help, depending on how MetricServiceClients are set up.

FWIW, we've had issues with the Cloud Bigtable client relating to UNAUTHENTICATED, and came up with a custom solution to the problem.  Ideally, our team gets that change into google-cloud-java as well.

**Comment by sduskis** [comment]
FYI, feel free to reach out offline.  My email address is on my [profile](https://github.com/sduskis).

**Comment by stiancognite** [comment]
A new MetricServiceClient is created each time the cron job is called, but maybe something is lingering? I'll try to confirm that I don't get the unauth error (the first time) after a new instance has been created..

A few minutes later: No unauth error on the next cron job execution. I'm guessing that's because a new instance of the app was created (I deleted the previous one).

After another 15 minutes: No unauth errors this time either. I'm guessing it'll take some time before the unauth error reappears after an access token has been created.

I'll send you an email tomorrow, after trying newer versions and perhaps a service account. Thanks!

**Comment by stiancognite** [comment]
This servlet has worked for about 24 hours now without any unauthenticated errors:
```
@WebServlet(name = "ScaleBigtable", value = "/bigtable")
public class ScaleBigtable extends HttpServlet {

  private static final Logger log = LoggerFactory.getLogger(ScaleBigtable.class);

  private static final String projectId = ***;
  private static final String instanceId = ***;
  private static final List<String> scopes =
      Collections.singletonList("https://www.googleapis.com/auth/monitoring");

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String result = null;

    AppIdentityService appIdentityService = AppIdentityServiceFactory
        .getAppIdentityService();
    String access_token = appIdentityService
        .getAccessToken(scopes)
        .getAccessToken();
    CredentialsProvider credentialsProvider = FixedCredentialsProvider
        .create(GoogleCredentials.getApplicationDefault().createScoped(scopes));
    credentialsProvider.getCredentials().refresh();
    MetricServiceSettings metricServiceSettings = MetricServiceSettings
        .newBuilder().setCredentialsProvider(credentialsProvider).build();

    try(
        MetricServiceClient metricServiceClient = MetricServiceClient.create(metricServiceSettings);
        BigtableClusterUtilities bigtableClusterUtilities = BigtableClusterUtilities
            .forInstance(projectId, instanceId)
    ) {
      Cluster cluster = bigtableClusterUtilities.getSingleCluster();
      BigtableClusterName bigtableClusterName = new BigtableClusterName(cluster.getName());
      // Create MetricScaler
      MetricScaler metricScaler = new MetricScaler(
          bigtableClusterUtilities,
          bigtableClusterName,
          metricServiceClient,
          BigtableClusterUtilities.getZoneId(cluster),
          ProjectName.create(projectId)
      );
      // Scale
      result = metricScaler.doScale();
    } catch (StatusRuntimeException | IllegalStateException | GeneralSecurityException | InterruptedException e) {
      log.error("ScaleBigtable.doGet() exception: " + e.getClass().getName() + ": " +
          e.getMessage(), e);
      response.sendError(500, e.getMessage());
    } catch (Exception e) {
      log.error("metricServiceClient.close() failed: " + e.getClass().getName() + ": " +
          e.getMessage(), e);
      response.sendError(500, e.getMessage());
    }

    if (!response.isCommitted()) {
      response.setContentType("text/plain");
      response.getWriter().println(result);
    }
  }

}
```

The `MetricScaler` is very similar to the one in the example, just modified to simplify testing. The critical thing that solved unauth errors was `credentialsProvider.getCredentials().refresh();`. The only thing I've noticed are 2-3 warnings of the type `com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor warn: Failed to refresh the access token. Falling back to existing token.`.

**Comment by stiancognite** [comment]
Sorry, forgot to close this.
