### ISSUE TITLE
Error when i try to start job hadoop in dataproc

### ISSUE THREAD

**Issue by NessrineBenZineb** [GoogleCloudPlatform/cloud-bigtable-examples#284]
I have these errors when i run this command: ./cluster.sh start cluster name.
Job [ed5aca53185d4c31bef29c1f77f672c3] submitted.
Waiting for job output...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in [jar:file:/tmp/ed5aca53185d4c31bef29c1f77f672c3/wordcount-mapreduce-0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
18/03/21 16:46:14 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.3-hadoop2
18/03/21 16:46:15 INFO sample.CreateTable: Creating Table WordCount-1521650758
18/03/21 16:46:15 INFO grpc.BigtableSession: Opening connection for projectId lucette-web-app, instanceId instance, on data host bigtable.googleapis.com, table admin host bigtableadmin.googleapis.com.
18/03/21 16:46:15 INFO grpc.BigtableSession: Bigtable options: BigtableOptions{dataHost=bigtable.googleapis.com, tableAdminHost=bigtableadmin.googleapis.com, instanceAdminHost=bigtableadmin.googleapis.com, projectId=lucette-web-app, instanceId=instance, userAgent=hbase-1.3.1, credentialType=DefaultCredentials, port=443, dataChannelCount=10, retryOptions=RetryOptions{retriesEnabled=true, allowRetriesWithoutTimestamp=false, statusToRetryOn=[UNAVAILABLE, ABORTED, DEADLINE_EXCEEDED, UNAUTHENTICATED, INTERNAL], initialBackoffMillis=5, maxElapsedBackoffMillis=60000, backoffMultiplier=2.0, streamingBufferSize=60, readPartialRowTimeoutMillis=60000, maxScanTimeoutRetries=3}, bulkOptions=BulkOptions{asyncMutatorCount=2, useBulkApi=true, bulkMaxKeyCount=25, bulkMaxRequestSize=1048576, autoflushMs=0, maxInflightRpcs=500, maxMemory=351220531, enableBulkMutationThrottling=false, bulkMutationRpcTargetMs=100}, callOptionsConfig=CallOptionsConfig{useTimeout=false, shortRpcTimeoutMs=60000, longRpcTimeoutMs=600000}, usePlaintextNegotiation=false}.
18/03/21 16:46:15 INFO io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
18/03/21 16:46:16 ERROR sample.CreateTable: Could not figure out if table WordCount-1521650758 exists.
java.io.IOException: Failed to listTables
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.requestTableList(AbstractBigtableAdmin.java:261)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:248)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:209)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.listTableNames(AbstractBigtableAdmin.java:201)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.tableExists(AbstractBigtableAdmin.java:144)
        at com.example.bigtable.sample.CreateTable.tableExists(CreateTable.java:89)
        at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:64)
        at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
        at com.example.bigtable.sample.WordCountDriver.main(WordCountDriver.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
        at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: projects/{475049264401}/instances/instance
        at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:340)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.listTables(BigtableTableAdminGrpcClient.java:93)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.requestTableList(AbstractBigtableAdmin.java:259)
        ... 22 more
18/03/21 16:46:17 ERROR sample.CreateTable: Could not create table WordCount-1521650758
java.io.IOException: Failed to create table 'WordCount-1521650758'
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:368)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:325)
        at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:73)
        at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
 at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
        at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: projects/{475049264401}/instances/instance
        at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:340)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.listTables(BigtableTableAdminGrpcClient.java:93)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.requestTableList(AbstractBigtableAdmin.java:259)
        ... 22 more
18/03/21 16:46:17 ERROR sample.CreateTable: Could not create table WordCount-1521650758
java.io.IOException: Failed to create table 'WordCount-1521650758'
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:368)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:325)
        at com.example.bigtable.sample.CreateTable.createTable(CreateTable.java:73)
        at com.example.bigtable.sample.WordCountHBase.main(WordCountHBase.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
        at com.example.bigtable.sample.WordCountDriver.main(WordCountDriver.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
        at com.google.cloud.hadoop.services.agent.job.shim.HadoopRunJarShim.main(HadoopRunJarShim.java:12)
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: projects/{475049264401}/instances/instance
        at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:340)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.createTable(BigtableTableAdminGrpcClient.java:105)
        at org.apache.hadoop.hbase.client.AbstractBigtableAdmin.createTable(AbstractBigtableAdmin.java:361)
        ... 18 more
18/03/21 16:46:17 INFO client.RMProxy: Connecting to ResourceManager at cluster-lucette-m/10.132.0.4:8032
18/03/21 16:46:20 INFO input.FileInputFormat: Total input files to process : 5
18/03/21 16:46:20 INFO mapreduce.JobSubmitter: number of splits:5
18/03/21 16:46:20 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1521218865062_0006
18/03/21 16:46:20 INFO impl.YarnClientImpl: Submitted application application_1521218865062_0006
18/03/21 16:46:20 INFO mapreduce.Job: The url to track the job: http://cluster-lucette-m:8088/proxy/application_1521218865062_0006/
18/03/21 16:46:20 INFO mapreduce.Job: Running job: job_1521218865062_0006
18/03/21 16:46:26 INFO mapreduce.Job: Job job_1521218865062_0006 running in uber mode : false
18/03/21 16:46:26 INFO mapreduce.Job:  map 0% reduce 0%
18/03/21 16:46:35 INFO mapreduce.Job:  map 20% reduce 0%
18/03/21 16:46:36 INFO mapreduce.Job:  map 40% reduce 0%
18/03/21 16:46:38 INFO mapreduce.Job:  map 60% reduce 0%
18/03/21 16:46:39 INFO mapreduce.Job:  map 80% reduce 0%
18/03/21 16:46:40 INFO mapreduce.Job:  map 100% reduce 0%
18/03/21 16:46:50 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000000_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 4830 actions: StatusRuntimeException: 4830 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:52 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000001_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 4276 actions: StatusRuntimeException: 4276 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:53 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000003_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 2359 actions: StatusRuntimeException: 2359 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:54 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000006_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1551 actions: StatusRuntimeException: 1551 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:54 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000004_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 3304 actions: StatusRuntimeException: 3304 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:55 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000002_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 2101 actions: StatusRuntimeException: 2101 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:55 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000005_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 3321 actions: StatusRuntimeException: 3321 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

18/03/21 16:46:57 INFO mapreduce.Job: Task Id : attempt_1521218865062_0006_r_000007_0, Status : FAILED
Error: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 3494 actions: StatusRuntimeException: 3494 times, servers with issues: bigtable.googleapis.com,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.flush(BigtableBufferedMutator.java:147)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:126)
        at org.apache.hadoop.hbase.client.AbstractBigtableConnection$2.close(AbstractBigtableConnection.java:185)
        at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:120)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

Any help please ?

**Comment by sduskis** [comment]
Here's the problem:

```
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Failed to read: projects/{475049264401}/instances/instance
```

Your Bigtable instance is not called "instance".
