### ISSUE TITLE
bigtable-shc: SBT assembly merge fails

### ISSUE THREAD

**Issue by alanroche** [GoogleCloudPlatform/cloud-bigtable-examples#330]
SBT assembly gives lots of merge duplication errors such as the below:
`deduplicate: different file contents found in the following:
/home/tiko/.ivy2/cache/org.apache.hadoop/hadoop-hdfs/jars/hadoop-hdfs-2.6.5.jar:org/apache/hadoop/fs/Hdfs$2.class`

See [assembly-stdout.txt](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/files/3798776/assembly-stdout.txt) for full error log.

I tried changing the sbt merge directives to have the following just to pick the first on merge conflict 
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/scala/bigtable-shc/build.sbt#L41

```  
case PathList("META-INF", xs @ _*) => MergeStrategy.discard

  case x => MergeStrategy.first
```

With the above the assembly gets created, but, then when I submit the job I get the error below, so I cannot trust that a wrong dependency was merged in:
`Caused by: com.google.bigtable.repackaged.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
        at com.google.bigtable.repackaged.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:60)
        at com.google.bigtable.repackaged.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:37)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableSession.createNettyChannel(BigtableSession.java:525)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableSession$3.create(BigtableSession.java:412)
        at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.ChannelPool.<init>(ChannelPool.java:246)`

**Comment by kolea2** [comment]
Closing as this sample has been updated/moved to: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/bigtable/spark. See https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/main/scala/bigtable-shc for more details.
